import ErdosTuzaValtr.Config.Lemmas
import ErdosTuzaValtr.Config.Mirror
import ErdosTuzaValtr.Config.Default
import ErdosTuzaValtr.Config.Defs
import ErdosTuzaValtr.Etv.Mirror
import ErdosTuzaValtr.Etv.Label
import ErdosTuzaValtr.Etv.Default
import ErdosTuzaValtr.Etv.AlphaBeta
import ErdosTuzaValtr.Etv.Defs
import ErdosTuzaValtr.Main.CapCup
import ErdosTuzaValtr.Main.Defs
import ErdosTuzaValtr.Main.InductionStep
import ErdosTuzaValtr.Main.Main
import ErdosTuzaValtr.Main.Lemmas.InterweavedLacedNGon
import ErdosTuzaValtr.Main.Lemmas.Default
import ErdosTuzaValtr.Main.Lemmas.JoinN2N2
import ErdosTuzaValtr.Main.Lemmas.JoinN2N3N2
import ErdosTuzaValtr.Main.Lemmas.JoinN2N3JoinN3N2
import ErdosTuzaValtr.Lib.Core.Rel3
import ErdosTuzaValtr.Lib.List.Chain3
import ErdosTuzaValtr.Lib.List.Lemmas
import ErdosTuzaValtr.Lib.List.Default
import ErdosTuzaValtr.Lib.List.Defs

#align_import Mathlib.all
